export { default as About } from './About'
export { default as Activities } from './Activities'
export { default as Categories } from './Categories'
export { default as Dashboard } from './Dashboard'
export { default as ForgotPassword } from './ForgotPassword'
export { default as Landing } from './Landing'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'